
---
- name: First Rulebook
  hosts: locahost
  sources:
    - name: range
      ansible.eda.range:
        limit: 5
  rules:
    - name: "Pring hello message"
      condition: event.i == 4
      action:
        run_playbook:
          name: ansible.eda.hello
